<tr><td>
<table border=0>
<hr>
<tr><td width=60%><div id="bottom"><span class="t_grey">ОАО &quot;Челябинский завод &quot;Теплоприбор&quot;. Все права защищены c 2004</span><br><br>
<p>Россия, 454047, г. Челябинск, ул. 2-я Павелецкая, 36<br>
<?php
$rn=rand(0,10);
if ($rn==0) 
	{
	 print '<strong>Иванов Олег Александрович</strong>,&#160; начальник отдела ПО OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-89-45, <a href="mailto:oaivanov@tpchel-eco.ru" shape="" coords="">oaivanov@tpchel-eco.ru</a>';
	}
if ($rn==1) 
	{
	 print '<strong>Скремета Всеволод Орестович</strong>,&#160; технический директор OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-74-95, <a href="mailto:skremeta@tpchel-eco.ru" shape="" coords="">skremeta@tpchel-eco.ru</a>';
	}
if ($rn==2 || $rn==3) 
	{
	 print '<strong>Стародубцев Сергей Владимирович</strong>,&#160; директор OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-76-31, <a href="mailto:svstarod@mail.tpchel.ru" shape="" coords="">svstarod@mail.tpchel.ru</a>';
	}
if ($rn==4) 
	{
	 print '<strong>Курнаков Иван Иванович</strong>,&#160; директор по инновациям OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-89-44, <a href="mailto:iikurnak@tpchel-eco.ru" shape="" coords="">iikurnak@tpchel-eco.ru</a>';
	}
if ($rn==5) 
	{
	 print '<strong>Серебряков Антон Валерьевич</strong>,&#160; ведущий инженер отдела ПО OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-89-45, <a href="mailto:anton@tpchel-eco.ru" shape="" coords="">anton@tpchel-eco.ru</a>';
	}
if ($rn==6 || $rn==7) 
	{
	 print '<strong>Перцев Семен Михайлович</strong>,&#160; начальник конструкторского отдела OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-89-45, <a href="mailto:pers@tpchel-eco.ru" shape="" coords="">pers@tpchel-eco.ru</a>';
	}
if ($rn==8) 
	{
	 print '<strong>Кутепов Алексей Валерьевич</strong>,&#160; направление Ультрагаз OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-75-90, <a href="mailto:avkutepo@tpchel-eco.ru" shape="" coords="">avkutepo@tpchel-eco.ru</a>';
	}
if ($rn>8) 
	{
	 print '<strong>Банников Евгений Владимирович</strong>,&#160; сотрудник группы АСКУЭР OOO "Теплоприбор-ЭКО"<br>';
	 print '+ 7 (351) 725-75-90, <a href="mailto:evbannik@tpchel-eco.ru" shape="" coords="">evbannik@tpchel-eco.ru</a>';
	}
?>
</strong></div></td>
<td width=30% align=left valign=top><div id="bottom"><div id="r_b">
<a href="http://askuer-server/88.php?menu=18" title="Баланс"><img src="files/attach.gif" alt="Баланс" border="0"></a>
<a href="http://askuer-server/88.php?menu=12" title="Отчеты"><img src="files/latest.gif" alt="Отчеты" border="0"></a>
<a href="http://askuer-server/88.php?menu=5" title="Пользователи"><img src="files/guests.gif" alt="Пользователи" border="0"></a>
<a href="http://askuer-server/88.php?menu=6" title="Узлы учета"><img src="files/uzli.gif" alt="Узлы учета" border="0"></a>
<a href="http://askuer-server/88.php?menu=2" title="Корпуса"><img src="files/home.gif" alt="Корпуса" border="0"></a>
<a href="http://askuer-server/forum.php" title="Обратная связь"><img src="files/feedback.gif" alt="Обратная связь" border="0"></a>
<a href="http://askuer-server/map.php" title="Карта"><img src="files/sitemap.gif" alt="Карта" border="0"></a></div></div></td>
<td width=10%><img src="files/l.gif" alt="Ростест" border="0"></td></tr>
</table></td></tr>
